### ISSUE TITLE
Cutscenes or Camera Manipulation. (no more cutscenes?)

### ISSUE THREAD

**Issue by MegaYTGaming** [CloneTrooper1019/Character-Realism#13]
So when i played and tested your first person it seems like the cutscenes didn't play due to first person script, And i decided to
try to disable the script to play cutscenes or camera manipulation and when the cutscene or camera manipulation ended i runned the script again which is: RealismClient, And an error showed up it says this script can be only runned for once, So that means if you died once the script will never play again?

(if you are asking why disable the script? because this is the only way i know how to play cutscenes when you have a custom first person those are steps that i know how to play cutscenes)

1. Disable first person script
2. Play cutscene or camera manipulation
3. When the cutscene ended, Run first person script

**Comment by CloneTrooper1019** [comment]
Why not just set the CameraType to Scriptable? It shouldn't be applying the first person patch if the camera is scriptable, and if it is then that's a bug I need to fix.

**Comment by MegaYTGaming** [comment]
Wait i thought your script makes camera type to scriptable, Welp i guess it's camera bobbing script but i haven't found the bug yet my studio crashed while ago, But i remember adding something that disturbs your script tho it's for thingy like body follows camera so it might be the one, Because when turning the camera type to custom or fixed, Because when the bug just happend the character was not walking straight it could have been disturbed by the script i added-

**Comment by MegaYTGaming** [comment]
I didn't realized that there was a thingy that makes body follows camera (waist and head r15) and yeah i think the bug is done but i'm not sure.

**Comment by MegaYTGaming** [comment]
https://streamable.com/91221p I forgot the other way how i made the bug appear, But i'm sure it acts like this-
