### ISSUE TITLE
the realism mod broke all of my roblox games

### ISSUE THREAD

**Issue by ZSwill** [CloneTrooper1019/Character-Realism#2]
when i got the scripts together it worked but the next day it broke so I deleted the scripts but it still says the realism rbxmx still there and it broke all of the games i made. is there a way to fix it?

**Comment by CloneTrooper1019** [comment]
Edited my response to request more clarification.

**Comment by ZSwill** [comment]
idk i did what I was supposed to do and it worked but then i saved the game left came back the next day and nothing worked and in the output it said user_Realism.rbxmx.Realism.RealismClient:108: attempt to index nil with 'Character' s I deleted it and it is still say the same i tried restarting it and my computer but nothing has changed. idk what is happening

**Comment by ZSwill** [comment]
<img width="211" alt="Untitled Tycoon - Roblox Studio 2020-12-06 6_12_28 PM" src="https://user-images.githubusercontent.com/75589366/101296403-50f7df80-37f1-11eb-980a-a0aa7c807e05.png">

**Comment by ZSwill** [comment]
i had the realism server in serverscriptservice and the client in starterplayer/starterplayerscripts

**Comment by CloneTrooper1019** [comment]
Oh that’s weird. See if you put it into your Plugins folder by accident.

**Comment by ZSwill** [comment]
no it is all deleted

**Comment by ZSwill** [comment]
![Untitled Tycoon - Roblox Studio 2020-12-06 6_48_09 PM](https://user-images.githubusercontent.com/75589366/101296829-a9c87780-37f3-11eb-9cfe-ec4efc030ddc.png)

**Comment by ZSwill** [comment]
my character is looking at the camera

**Comment by CloneTrooper1019** [comment]
Click the Plugins tab at the top and click the blue button that says Open Plugins Folder.

If you see Realism.rbxm in there, delete it.

**Comment by ZSwill** [comment]
i did it but in the output it still says the same thing the only change is that my character isn't looking at the camera

**Comment by ZSwill** [comment]
i will try restarting roblox studios again

**Comment by ZSwill** [comment]
oh fixed

**Comment by ZSwill** [comment]
thanks
