### ISSUE TITLE
Issues with arm movement.

### ISSUE THREAD

**Issue by StudBoard** [CloneTrooper1019/Character-Realism#4]
It seems as the left arm when you look down or look up doesn't move along with your right arm.
![image](https://user-images.githubusercontent.com/58184279/102539021-b742f480-4072-11eb-8131-2e9273284cc4.png)
I've also seem to find even major problems with it, the left arm seems to just not work with the script.
![image](https://user-images.githubusercontent.com/58184279/102546837-df842080-407d-11eb-9809-2ff7e13fc587.png)

**Comment by kinkocat** [comment]
I don't know if this pertains to this issue but the "Left Arm" is always marked as "Dirty" in the code & as a result it will never be rotated during the heartbeat loop. I added:

```lua
if Dirty or name:sub(1, 4) == "Left" then
          -- Rest of the code here.
end
```
