### ISSUE TITLE
Client sanity checks don't allow RealismClient to be placed within folders under StarterPlayerScripts

### ISSUE THREAD

**Issue by higbead** [CloneTrooper1019/Character-Realism#5]
![New Project (2)](https://user-images.githubusercontent.com/63697850/103145203-d76e5580-46fb-11eb-9a75-818c56b146da.png)
This *should* work, but doesn't purely because the parent sanity check only accounts for the direct parent of the script. If I disable the check, everything works fine.

![image](https://user-images.githubusercontent.com/63697850/103145212-18ff0080-46fc-11eb-9b99-4e0fa8378dbd.png)
This can probably be fixed simply by replacing `script.Parent:IsA("PlayerScripts")` with something along the lines of `script:FindFirstAncestorWhichIsA("PlayerScripts")`.

**Comment by CloneTrooper1019** [comment]
Sorry I’m only seeing this now. I’ll have a patch shortly.

**Comment by CloneTrooper1019** [comment]
Easy enough of a change. I’ll have this built into Realism.rbxm later today.
https://github.com/CloneTrooper1019/Character-Realism/commit/5d0b9cf3a5a0b6415c5c36c1e1f69af9d4652271
